#!/bin/sh

set -e

chown -R frr:frr /etc/frr

sleep 1
/usr/lib/frr/frrinit.sh start

# Restart to be sure everything is up-to-date
sleep 1
/usr/lib/frr/frrinit.sh restart

# Sleep forever
exec tail -f /dev/null